name: Check links

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main  # Trigger action on pull request to main branch

jobs:
  htmltest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'

      - name: Build
        run: hugo --minify

      - name: Run htmltest
        uses: wjdp/htmltest-action@master
        with:
          path: public

      - name: Archive htmltest results
        uses: actions/upload-artifact@v2
        with:
          name: htmltest-report
          path: tmp/.htmltest/htmltest.log
          retention-days: 7
